import type { StayRegistration } from "@prisma/client";

export function stayRegistrationPdfHtml(sr: any) {
  // sr puede venir con joins (booking, room, etc.)
  const safe = (v: any) => (v == null || v === "" ? "-" : String(v));

  return `
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Police Report - Stay Registration #${sr.id}</title>
  <style>
    body { font-family: Arial, sans-serif; font-size: 12px; color: #111; }
    h1 { font-size: 18px; margin: 0 0 6px; }
    h2 { font-size: 13px; margin: 18px 0 8px; }
    .muted { color: #555; }
    .box { border: 1px solid #ddd; border-radius: 8px; padding: 10px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 14px; }
    .row { display: flex; gap: 6px; }
    .label { font-weight: bold; min-width: 140px; }
    .footer { margin-top: 18px; font-size: 11px; color: #555; }
    hr { border: none; border-top: 1px solid #eee; margin: 12px 0; }
  </style>
</head>
<body>
  <h1>Police Report (Stay Registration)</h1>
  <div class="muted">Registration ID: ${sr.id} • Hotel ID: ${sr.hotelId} • Booking ID: ${sr.bookingId}</div>
  <hr/>

  <h2>Guest Snapshot</h2>
  <div class="box">
    <div class="grid">
      <div class="row"><div class="label">Name:</div><div>${safe(sr.guestName)}</div></div>
      <div class="row"><div class="label">Email:</div><div>${safe(sr.guestEmail)}</div></div>
      <div class="row"><div class="label">Phone:</div><div>${safe(sr.guestPhone)}</div></div>
      <div class="row"><div class="label">Nationality:</div><div>${safe(sr.nationality)}</div></div>
      <div class="row"><div class="label">Document Type:</div><div>${safe(sr.documentType)}</div></div>
      <div class="row"><div class="label">Document Number:</div><div>${safe(sr.documentNumber)}</div></div>
      <div class="row"><div class="label">Birth Date:</div><div>${safe(sr.birthDate ? new Date(sr.birthDate).toLocaleDateString() : null)}</div></div>
      <div class="row"><div class="label">Gender:</div><div>${safe(sr.gender)}</div></div>
      <div class="row"><div class="label">Address:</div><div>${safe(sr.address)}</div></div>
      <div class="row"><div class="label">City:</div><div>${safe(sr.city)}</div></div>
      <div class="row"><div class="label">Country:</div><div>${safe(sr.country)}</div></div>
    </div>
  </div>

  <h2>Stay Snapshot</h2>
  <div class="box">
    <div class="grid">
      <div class="row"><div class="label">Room:</div><div>${sr.room?.number ? `Room ${sr.room.number} (floor ${sr.room.floor})` : safe(sr.roomId)}</div></div>
      <div class="row"><div class="label">Scheduled Check-in:</div><div>${safe(sr.scheduledCheckIn ? new Date(sr.scheduledCheckIn).toLocaleString() : null)}</div></div>
      <div class="row"><div class="label">Scheduled Check-out:</div><div>${safe(sr.scheduledCheckOut ? new Date(sr.scheduledCheckOut).toLocaleString() : null)}</div></div>
      <div class="row"><div class="label">Checked-in At:</div><div>${safe(sr.checkedInAt ? new Date(sr.checkedInAt).toLocaleString() : null)}</div></div>
      <div class="row"><div class="label">Checked-out At:</div><div>${safe(sr.checkedOutAt ? new Date(sr.checkedOutAt).toLocaleString() : null)}</div></div>
      <div class="row"><div class="label">Created At:</div><div>${safe(sr.createdAt ? new Date(sr.createdAt).toLocaleString() : null)}</div></div>
    </div>
  </div>

  <div class="footer">
    Generated by HotelManager • ${new Date().toLocaleString()}
  </div>
</body>
</html>
`;
}
